USE procurement;

CREATE TABLE IF NOT EXISTS procurement_methods (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  procurement_method VARCHAR(150) NOT NULL UNIQUE,
  details TEXT NULL,
  status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
