<?php
require_once __DIR__.'/../config/config.php';
requireRole(['Administrator','Editor','Viewer','Guest']); require_once __DIR__.'/../app/layout.php';
$year=(int)($_GET['year']??date('Y'));$pdo=db();
$contextDivisionId=currentLoginDivisionId();$contextAreaId=currentLoginAreaId();$isSupervisor=currentUserIsPpmpSupervisor();
$pendingPpmpCount=0;
if($isSupervisor && $contextDivisionId>0){$pendingSt=$pdo->prepare("SELECT COUNT(*) FROM ppmp_reviews r JOIN areas a ON a.id=r.area_id WHERE r.status='Pending for Review' AND a.division_id=?");$pendingSt->execute([$contextDivisionId]);$pendingPpmpCount=(int)$pendingSt->fetchColumn();}
$scopeSql='';$scopeArgs=[];
if($isSupervisor && $contextDivisionId>0){$scopeSql=' JOIN areas sa ON sa.id=p.area_id WHERE p.fiscal_year=? AND sa.division_id=?';$scopeArgs=[$year,$contextDivisionId];}
elseif($contextAreaId>0){$scopeSql=' WHERE p.fiscal_year=? AND p.area_id=?';$scopeArgs=[$year,$contextAreaId];}
else{$scopeSql=' WHERE p.fiscal_year=?';$scopeArgs=[$year];}
$ppmpSt=$pdo->prepare("SELECT COUNT(*) FROM ppmp_items p".$scopeSql);$ppmpSt->execute($scopeArgs);$ppmp=(int)$ppmpSt->fetchColumn();
$areaSt=$pdo->prepare("SELECT COUNT(DISTINCT p.area_id) FROM ppmp_items p".$scopeSql);$areaSt->execute($scopeArgs);$areas=(int)$areaSt->fetchColumn();
$qtySt=$pdo->prepare("SELECT COALESCE(SUM(p.quantity),0) FROM ppmp_items p".$scopeSql);$qtySt->execute($scopeArgs);$qty=(float)$qtySt->fetchColumn();
$abcSt=$pdo->prepare("SELECT COALESCE(SUM(p.quantity*p.unit_price),0) FROM ppmp_items p".$scopeSql);$abcSt->execute($scopeArgs);$abc=(float)$abcSt->fetchColumn();
$prWhere=$isSupervisor&&$contextDivisionId>0?' AND a.division_id=?':($contextAreaId>0?' AND r.area_id=?':'');
$prArgs=$isSupervisor&&$contextDivisionId>0?[$year,$contextDivisionId]:($contextAreaId>0?[$year,$contextAreaId]:[$year]);
$prCountSt=$pdo->prepare("SELECT COUNT(*) FROM purchase_requests r JOIN areas a ON a.id=r.area_id WHERE r.fiscal_year=? AND r.status<>'Cancelled'".$prWhere);$prCountSt->execute($prArgs);$prCount=(int)$prCountSt->fetchColumn();
$poCountSt=$pdo->prepare("SELECT COUNT(*) FROM purchase_orders o JOIN purchase_requests r ON r.id=o.pr_id JOIN areas a ON a.id=r.area_id WHERE r.fiscal_year=? AND o.status<>'Cancelled'".$prWhere);$poCountSt->execute($prArgs);$poCount=(int)$poCountSt->fetchColumn();
$recentSql=$isSupervisor&&$contextDivisionId>0?' WHERE p.fiscal_year=? AND a.division_id=?':($contextAreaId>0?' WHERE p.fiscal_year=? AND p.area_id=?':' WHERE p.fiscal_year=?');
$recentArgs=$isSupervisor&&$contextDivisionId>0?[$year,$contextDivisionId]:($contextAreaId>0?[$year,$contextAreaId]:[$year]);
$recent=$pdo->prepare('SELECT p.*,a.name area,c.name category FROM ppmp_items p JOIN areas a ON a.id=p.area_id JOIN categories c ON c.id=p.category_id'.$recentSql.' ORDER BY p.created_at DESC LIMIT 8');$recent->execute($recentArgs);pageStart('Dashboard');
?><div class="panel" style="margin-bottom:16px"><h2>Current Login Context</h2><p><b>Division/Department:</b> <?=e(loginContext()['division_name']??'')?></p><p><b>Area/Unit:</b> <?=e(loginContext()['area_name']??'All Areas/Units in Division')?></p><?php if($isSupervisor): ?><p><span class="badge">Supervisor/Authorized Person — PPMP Review Access</span></p><div style="margin-top:12px"><a class="btn" href="ppmp.php">Project Procurement Management Plan</a><?php if($pendingPpmpCount>0): ?> <span class="ppmp-status-badge ppmp-status-pending-for-review" style="margin-left:8px"><?=number_format($pendingPpmpCount)?> PPMP<?=($pendingPpmpCount===1?'':'s')?> Pending for Review</span><?php endif; ?></div><?php endif; ?></div><div class="cards"><div class="card"><div class="label">PPMP Line Items</div><div class="metric"><?=number_format($ppmp)?></div><div class="hint">FY <?=$year?></div></div><div class="card"><div class="label">Participating Areas/Units</div><div class="metric"><?=number_format($areas)?></div><div class="hint">With submitted PPMP items</div></div><div class="card"><div class="label">Total Planned Quantity</div><div class="metric"><?=number_format($qty,2)?></div><div class="hint">Across all PPMPs</div></div><div class="card"><div class="label">Total Planned ABC</div><div class="metric">₱<?=number_format($abc,2)?></div><div class="hint">Quantity × unit price</div></div></div>
<div class="cards" style="margin-top:16px"><div class="card"><div class="label">Purchase Requests</div><div class="metric"><?=number_format($prCount)?></div><div class="hint">Non-cancelled FY <?=$year?></div></div><div class="card"><div class="label">Purchase Orders</div><div class="metric"><?=number_format($poCount)?></div><div class="hint">Non-cancelled FY <?=$year?></div></div></div>
<div class="grid"><div class="panel"><h2>Recent PPMP Entries</h2><div class="table-wrap"><table class="table"><tr><th>Item</th><th>Area/Unit</th><th>Category</th><th>Qty</th><th>ABC</th></tr><?php foreach($recent as $r):?><tr><td><?=e($r['item_name'])?></td><td><?=e($r['area'])?></td><td><?=e($r['category'])?></td><td><?=number_format($r['quantity'],2).' '.e($r['unit'])?></td><td>₱<?=number_format($r['quantity']*$r['unit_price'],2)?></td></tr><?php endforeach;?></table></div></div><div class="panel"><h2>Procurement Workflow</h2><p>1. Area/Unit prepares its PPMP.</p><p>2. Equivalent PPMP items are consolidated into the APP.</p><p>3. Authorized users create PRs from available PPMP quantities.</p><p>4. PR quantities automatically reduce remaining planned quantities.</p><p>5. Submitted/approved PRs can be converted into POs with supplier details.</p><a class="btn" href="app.php?year=<?=$year?>">View Consolidated APP</a></div></div><?php pageEnd();