<?php
require_once __DIR__.'/../config/config.php';
require_once __DIR__.'/../config/config.php';
<?php
requireRole(['Administrator','Editor','Viewer','Guest']); require_once __DIR__.'/../app/layout.php'; $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){requireRole(['Administrator','Editor']);checkCsrf();$st=$pdo->prepare('INSERT INTO ppmp_items(fiscal_year,area_id,category_id,item_name,description,quantity,unit,unit_price,requested_by,remarks,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$st->execute([(int)$_POST['fiscal_year'],(int)$_POST['area_id'],(int)$_POST['category_id'],trim($_POST['item_name']),trim($_POST['description']),max(0,(float)$_POST['quantity']),trim($_POST['unit']),max(0,(float)$_POST['unit_price']),trim($_POST['requested_by']),trim($_POST['remarks']),currentUser()['id']]);flash('success','PPMP item saved.');header('Location:ppmp.php');exit;}
$areas=$pdo->query('SELECT * FROM areas ORDER BY name')->fetchAll();$cats=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();$year=(int)($_GET['year']??date('Y'));$q=trim($_GET['q']??'');$sql='SELECT p.*,a.name area,c.name category FROM ppmp_items p JOIN areas a ON a.id=p.area_id JOIN categories c ON c.id=p.category_id WHERE p.fiscal_year=?';$args=[$year];if($q!==''){$sql.=' AND (p.item_name LIKE ? OR a.name LIKE ? OR c.name LIKE ?)';$args=[...$args,"%$q%","%$q%","%$q%"];}$sql.=' ORDER BY p.created_at DESC';$st=$pdo->prepare($sql);$st->execute($args);$rows=$st->fetchAll();pageStart('Project Procurement Management Plan');
?><div class="panel"><div class="toolbar"><form><input class="input" name="q" placeholder="Search item, area or category" value="<?=e($q)?>"><input type="hidden" name="year" value="<?=$year?>"></form><?php if(hasRole(['Administrator','Editor'])):?><button class="btn" onclick="document.getElementById('ppmpForm').scrollIntoView();return false">+ Add PPMP Item</button><?php endif;?></div><div class="table-wrap"><table class="table"><tr><th>FY</th><th>Item</th><th>Area/Unit</th><th>Category</th><th>Qty</th><th>Unit Price</th><th>ABC</th><th>Entered By</th></tr><?php foreach($rows as $r):?><tr><td><?=$r['fiscal_year']?></td><td><b><?=e($r['item_name'])?></b><br><small><?=e($r['description'])?></small></td><td><?=e($r['area'])?></td><td><?=e($r['category'])?></td><td><?=number_format($r['quantity'],2).' '.e($r['unit'])?></td><td>₱<?=number_format($r['unit_price'],2)?></td><td>₱<?=number_format($r['quantity']*$r['unit_price'],2)?></td><td><?=e($r['requested_by'])?></td></tr><?php endforeach;?></table></div></div>
<?php if(hasRole(['Administrator','Editor'])):?><div class="panel" id="ppmpForm" style="margin-top:18px"><h2>New PPMP Item</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><div class="form-grid"><div class="field"><label>Fiscal Year</label><input class="input" type="number" name="fiscal_year" value="<?=$year?>" min="2020" max="2100" required></div><div class="field"><label>Area/Unit</label><select class="select" name="area_id" required><option value="">Select</option><?php foreach($areas as $a):?><option value="<?=$a['id']?>"><?=e($a['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Category</label><select class="select" name="category_id" required><option value="">Select</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Item Name</label><input class="input" name="item_name" required placeholder="e.g. Bond Paper A4 80gsm"></div><div class="field"><label>Quantity</label><input class="input" type="number" step="0.0001" min="0" name="quantity" required></div><div class="field"><label>Unit</label><input class="input" name="unit" required placeholder="ream, pcs, box, lot..."></div><div class="field"><label>Unit Price</label><input class="input" type="number" step="0.01" min="0" name="unit_price" required></div><div class="field"><label>Requested By</label><input class="input" name="requested_by"></div><div class="field full"><label>Description</label><textarea class="input" name="description" rows="2"></textarea></div><div class="field full"><label>Remarks</label><textarea class="input" name="remarks" rows="2"></textarea></div></div><div class="actions"><button class="btn" type="submit">Save PPMP</button></div></form></div><?php endif;?><?php pageEnd();
